
services:
  notification:
    image: imjunhyuk/urecar_notification:latest
    container_name: notification
    ports:
      - "8082:8082"
      - "8083:8083"
    volumes:
      - ./service-account.json:/home/ubuntu/docker/notification/service-account.json
    networks:
      - urecar_network
    environment:
      SPRING_PROFILES_ACTIVE: prod


networks:
  urecar_network:
    external: true

